In [4]:
import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

In [5]:
train_data = pd.read_csv("samsum-train.csv")
val_data = pd.read_csv("samsum-validation.csv")

In [7]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [9]:
train_data.shape

(14732, 3)

In [10]:
val_data.shape

(818, 3)

In [11]:
train_data = train_data.sample(n=4000, random_state=42).reset_index(drop=True)
val_data = val_data.sample(n=500, random_state=42).reset_index(drop=True)

In [12]:
train_data.shape

(4000, 3)

# Data Pre-processing

In [14]:
import re 

def clean_text(text):
    text = re.sub(r"\r\n", " ", text) #lines
    text = re.sub(r"\s+", " ", text) #spaces
    text = re.sub(r"\<.*?>", " ", text) #html tags
    text = text.strip().lower()
    return text

In [18]:
train_data["dialogue"] = train_data["dialogue"].apply(clean_text)
train_data["summary"] = train_data["summary"].apply(clean_text)

val_data["dialogue"] = val_data["dialogue"].apply(clean_text)
val_data["summary"] = val_data["summary"].apply(clean_text)

In [19]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.json: 0.00B [00:00, ?B/s]

In [29]:
# raw data --> tokenized input for fine tuning

def tokenize(data):
    inputs = tokenizer(data["dialogue"], padding="max_length", max_length=512, truncation=True)
    target = tokenizer(data["summary"], padding="max_length", max_length=150, truncation=True)

    inputs["labels"] = target["input_ids"] #target token ids ==> add to input as labels
    return inputs

In [30]:
train_dataset = train_data.apply(tokenize, axis=1).tolist()
val_dataset = val_data.apply(tokenize, axis=1).tolist()

In [31]:
# input ids - dialogue => token ids

# 1 => EOS, 0 => padding

# attention mask
# labels - target => summary token

In [32]:
len(train_dataset[0]["input_ids"])

512

# Working with the model

In [33]:
# NLP ==> generation task

model = T5ForConditionalGeneration.from_pretrained("t5-small")

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [34]:
# fine-tune
import torch
#Model requires a hardware to run on and 
#This code check which hardware is available then..

if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_availanle():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print("device: ", device)
model.to(device) # Send the model to that device(hardware)

device:  mps

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
)

In [37]:
#Training arguments

training_args = TrainingArguments(
    output_dir = "./results",

    num_train_epochs=6,
    weight_decay=0.01,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    eval_strategy="epoch",
    save_strategy="epoch",

    warmup_steps=500
    # 0 => lr default
)

In [38]:
trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = val_dataset
)

In [39]:
#Train the model
trainer.train()

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d676230>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161861e60>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x167065be0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161874f10>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x167063ff0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1670fd490>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1670f9170>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x167067c00>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161cf06c0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6d2720>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x167073460>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab0e060>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1670ffc90>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6c93c0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6af760>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161cf9cc0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161871270>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16706fb30>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161cf52e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16705af90>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x167071c60>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1670115b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1670fc1b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab0ff80>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16186ac70>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6b43f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d699730>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16700f0e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6b0950>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6b2840>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16706b800>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161cf34c0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6a02b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161cfb780>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x167065920>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab13cc0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x167073bb0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161861800>
    label = <none>

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6ea550>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d685a40>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161c7a800>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161c7fc00>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161c7df00>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x329953250>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32992c110>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x329970bb0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x329948880>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6e2b40>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x329904860>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662ecc30>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662fd440>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662f95d0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1670d3fc0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6a2a70>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1670d44c0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161c74520>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32998d6f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32998bab0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662ec490>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6229e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3299556c0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x329993570>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662fd2d0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662f6c00>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d61cff0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662ed130>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32992d350>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662f8dc0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161c45fd0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x329938540>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d615230>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d685780>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6e4b50>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d6e46b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12d618f80>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001c6970>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x300194110>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x300186d70>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab638a0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x30019d670>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab84270>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001c3ab0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001a1cf0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001ae770>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x166218390>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab4eb50>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x30019e4d0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x300161e70>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001b7790>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001a2150>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x300182890>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001cb080>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001a84a0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x300197580>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x30015e840>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab6e520>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab6f540>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x300177fa0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab6c660>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab5c810>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab843e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab7f3d0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab590f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x30015c6b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x30018fcb0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001a0160>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001bc820>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32aba7c20>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x300161130>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001ba720>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x300180380>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x300155430>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662f06e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662bd540>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab49a50>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abfeb70>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abfe470>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12c1d2020>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x166207950>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab4c730>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abb7ba0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab63ce0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abfa6c0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662aed20>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662f4510>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abd29b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abc7f00>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab796b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662f0f50>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abb60d0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab6e1d0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32aba73c0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12c1ae8f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab5dbb0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abacc10>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab252e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab2ebb0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662ea660>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abb7ba0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12c1da960>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32aba8c70>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab57970>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abffbd0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abd16f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662bdbd0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab23e20>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x12c1d6980>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abb8eb0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32aba2fb0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1662a28d0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab34ee0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab29dc0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abff7b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abbea80>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32aba3e00>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab86170>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab7b610>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d68d950>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab48060>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab06ce0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d665be0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d690120>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001a0bb0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abd6ed0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab24bf0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x3001b7600>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x30017b9e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab1ad50>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab1ca00>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab51c00>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1670d4bd0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab8d480>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d62b770>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d6674f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab7ffd0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abc9000>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d653e10>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abd5b20>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d68a800>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d6489f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abb8600>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d6a49c0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab4c2b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d6b3850>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abaf230>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d6b2950>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d6d56e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d64d330>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618e1640>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618a4780>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abd0cc0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618d2ce0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abd8620>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abe32c0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16187c1f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618f1c90>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d6eedb0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16667e280>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618b8220>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618d10b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618f0290>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16188ea80>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618d3e80>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16184a2f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618da1b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16187e710>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618ce9b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab285e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d6d56e0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abec5b0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618c3070>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16184f010>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161899480>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32abd9f30>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618869f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x161856270>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x32ab897f0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618cf950>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x16184b030>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618c9b80>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618b1cd0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x1618df9a0>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error:
	(null)
	Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
	<AGXG14GFamilyCommandBuffer: 0x13d6e4300>
    label = <none>
    device = <AGXG14GDevice: 0x31f187600>
        name = Apple M2
    commandQueue = <AGXG14GFamilyCommandQueue: 0x31f14fa00>
        label = <none>
        device = <AGXG14GDevice: 0x31f187600>
            name = Apple M2
    retainedReferences = 1
Error: command buffer exited with error status.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=3000, training_loss=15.353409342447916, metrics={'train_runtime': 50669.3445, 'train_samples_per_second': 0.474, 'train_steps_per_second': 0.059, 'total_flos': 3248203235328000.0, 'train_loss': 15.353409342447916, 'epoch': 6.0})

In [40]:
#save the model
model.save_pretrained("./saved_summary_model")
tokenizer.save_pretrained("./saved_summary_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./saved_summary_model/tokenizer_config.json',
 './saved_summary_model/tokenizer.json')

In [42]:
#load the model
model = T5ForConditionalGeneration.from_pretrained("./saved_summary_model")
tokenizer = T5Tokenizer.from_pretrained("./saved_summary_model")

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

## Test the core logic for summarization

In [51]:
def summarize_dialogue(dialogue):
    dialogue = clean_text(dialogue) #Clean
    
    #Tokenize
    inputs = tokenizer(
        dialogue,
        padding = "max_length",
        max_length = 512,
        truncate = True,
        return_tensors = "pt"
    ).to(device)

    #Generate the summary ==> token ids
    model.to(device)
    targets = model.generate(
        input_ids = inputs["input_ids"],
        attention_mask = inputs["attention_mask"],
        num_beams = 4, #4 summary bnegi unme se sbse best selected
        max_length = 150,
        early_stopping = True
    )

    #decode the output
    summary = tokenizer.decode(targets[0],skip_special_tokens=True)
    return summary

In [54]:
test_dialogue = """ 
Reporter: In today's technology news, artificial intelligence continues to expand rapidly across industries, from healthcare to finance and education. Recent reports suggest that AI adoption has significantly increased over the past few years.

Reporter: Companies are investing heavily in machine learning systems to automate tasks, improve decision-making, and enhance customer experiences. However, this growth has also raised questions about job displacement and ethical concerns.

Expert: AI systems are becoming more capable due to advances in deep learning and access to large datasets. These models can now perform complex tasks such as language understanding, image recognition, and even code generation.

Expert: At the same time, there are valid concerns about bias in AI models, as they often reflect the data they are trained on. Ensuring fairness and transparency is becoming a key area of research.

Reporter: Governments and organizations are beginning to introduce regulations to guide the development and deployment of AI technologies. The goal is to balance innovation with accountability.

Expert: Another challenge is explainability. Many modern AI systems, especially deep neural networks, operate as “black boxes,” making it difficult to understand how decisions are made.

Reporter: Experts also highlight the importance of responsible AI development, including data privacy, security, and long-term societal impact.

Expert: Looking ahead, collaboration between researchers, policymakers, and industry leaders will be crucial to ensure that AI systems are developed and used in a safe and beneficial way.
"""

summary = summarize_dialogue(test_dialogue)
print("summary :", summary)

summary : experts highlight the importance of responsible ai development, including data privacy, security, and long-term societal impact. ensuring fairness and transparency is becoming a key area of research.